default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  database: swoope_development
  <<: *default


test:
  database: swoope_test
  <<: *default


production:
  database: swoope_production
  <<: *default


