defaults: &defaults
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  database: mpos_dev
  <<: *defaults

test:
  database: mpos_test
  <<: *defaults

production:
  database: mpos_dev
  <<: *defaults
